const ADD_ITEM = 'ADD_ITEM';
const DEL_ITEM = 'DEL_ITEM';
const CLEAR_LIST = 'CLEAR_LIST';
const UPDATE_ITEM = 'UPDATE_ITEM';
const TOGGLE_PURCHASE = 'TOGGLE_PURCHASE';


export {
  ADD_ITEM,
  DEL_ITEM,
  CLEAR_LIST,
  UPDATE_ITEM,
  TOGGLE_PURCHASE,
};
